all: seq

seq:
	gcc run-gen-configs-gemm.c -o run-gen-configs-gemm.exe
	gcc run-gen-configs-atax.c -o run-gen-configs-atax.exe
	gcc run-gen-configs-sincos.c -o run-gen-configs-sincos.exe
	
clean:
	rm *.exe

